//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var image: image { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 9 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// en translation: Blog
      ///
      /// Key: blog
      ///
      /// Locales: en
      var blog: RswiftResources.StringResource { .init(key: "blog", tableName: "Localizable", source: source, developmentValue: "Blog", comment: nil) }

      /// en translation: Close
      ///
      /// Key: common_close
      ///
      /// Locales: en
      var common_close: RswiftResources.StringResource { .init(key: "common_close", tableName: "Localizable", source: source, developmentValue: "Close", comment: nil) }

      /// en translation: OK
      ///
      /// Key: common_ok
      ///
      /// Locales: en
      var common_ok: RswiftResources.StringResource { .init(key: "common_ok", tableName: "Localizable", source: source, developmentValue: "OK", comment: nil) }

      /// en translation: Retry
      ///
      /// Key: common_retry
      ///
      /// Locales: en
      var common_retry: RswiftResources.StringResource { .init(key: "common_retry", tableName: "Localizable", source: source, developmentValue: "Retry", comment: nil) }

      /// en translation: Followers
      ///
      /// Key: followers
      ///
      /// Locales: en
      var followers: RswiftResources.StringResource { .init(key: "followers", tableName: "Localizable", source: source, developmentValue: "Followers", comment: nil) }

      /// en translation: Followers
      ///
      /// Key: following
      ///
      /// Locales: en
      var following: RswiftResources.StringResource { .init(key: "following", tableName: "Localizable", source: source, developmentValue: "Followers", comment: nil) }

      /// en translation: User Details
      ///
      /// Key: git_user_detail_screen_title
      ///
      /// Locales: en
      var git_user_detail_screen_title: RswiftResources.StringResource { .init(key: "git_user_detail_screen_title", tableName: "Localizable", source: source, developmentValue: "User Details", comment: nil) }

      /// en translation: Github Users
      ///
      /// Key: git_user_list_screen_title
      ///
      /// Locales: en
      var git_user_list_screen_title: RswiftResources.StringResource { .init(key: "git_user_list_screen_title", tableName: "Localizable", source: source, developmentValue: "Github Users", comment: nil) }

      /// en translation: Not set
      ///
      /// Key: not_set
      ///
      /// Locales: en
      var not_set: RswiftResources.StringResource { .init(key: "not_set", tableName: "Localizable", source: source, developmentValue: "Not set", comment: nil) }
    }
  }

  /// This `_R.image` struct is generated, and contains static references to 1 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `ImageAvatarPlaceHolder`.
    var imageAvatarPlaceHolder: RswiftResources.ImageResource { .init(name: "ImageAvatarPlaceHolder", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.file` struct is generated, and contains static references to 2 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `.gitkeep`.
    var gitkeep: RswiftResources.FileResource { .init(name: ".gitkeep", pathExtension: "", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `GitUserSample.plist`.
    var gitUserSamplePlist: RswiftResources.FileResource { .init(name: "GitUserSample", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }
  }
}